### ISSUE TITLE
cargo test

### ISSUE THREAD

**Issue by tpisto** [penberg/tihku#59]
Even though this repo is WIP, just quickly to let you know (you might already do) but when running tests, one test fails:
test database::tests::test_lost_update ... FAILED

**Comment by penberg** [comment]
@tpisto Thanks for opening the issue, I can reproduce it here as well. /cc @psarna

**Comment by psarna** [comment]
will check, thanks! I wonder how it made its way through CI... maybe it's a flaky test and only passes because of a race or something
