### ISSUE TITLE
Row data type

### ISSUE THREAD

**Issue by tpisto** [penberg/tihku#60]
This is more of a question than an issue. Have you planned to use generic row data type instead of String?

```
pub struct Row<T> {
    pub id: RowID,
    pub data: T,
}
```

I tried to implement the Row<T> in my fork (https://github.com/tpisto/tihku) and it's mostly working, tests are passing, etc. But the self.rows.remove(&id) gives a lifetime issue I have not yet managed to solve... If Row<T> is in your interest, maybe you could have better insight what's wrong the lifetime there.

ps. congrats for the cool project 👍🏻

**Comment by tpisto** [comment]
I added 'static bounds to T, and everything works now in my fork. 

'static bound is known limitation of skiplist and could be removed in the future.
https://github.com/crossbeam-rs/crossbeam/issues/205

**Comment by penberg** [comment]
@tpisto Haha, yes, we've just been to lazy to do this. If you got the lifetime issues sorted out, can you please open a pull request? I think I will need @psarna to review it because he's was the one doing the switch to lockless skip list.
